name: Lint

on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/lint.yml
      - .swiftlint.yml
      - "**/*.swift"

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: norio-nomura/action-swiftlint@3.2.1
