name: Test

on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/test.yml
      - "Sources/**"
      - "Tests/**"

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: 5.4
      - run: swift build
      - run: swift test
